version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

  chrome:
    image: selenium/node-chrome:4.21.0
    container_name: chrome-node
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: '2gb'

  firefox:
    image: selenium/node-firefox:4.21.0
    container_name: firefox-node
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: '2gb'

  edge:
    image: selenium/node-edge:4.21.0
    container_name: edge-node
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: '2gb'

networks:
  selenium-grid:
    driver: bridge
